channels:
  - defaults
  - conda-forge
dependencies:
  - ipywidgets
  - keras
  - matplotlib
  - pandas
  - numpy
  - tensorflow==2.2
  - ipython
  - ipykernel  
  - networkx
  - tikzmagic
  - tensorflow-gpu
  - cudatoolkit
  - pydotplus
  - graphviz
  - pip
  - pip:
    - pyocclient

